id: P000009
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD95844
  title: བསྟན་འགྱུར། ༼དཔེ་བསྡུར་མ༽
  author: ''
  volumes:
    dbf9e8e4682d45d08efdfe3955b19314:
      image_group_id: I1PD95846
      title: ''
      volume_number: 1
      total_pages: 1539
    ddd6f555295d40b08b29c194e2971d56:
      image_group_id: I1PD95847
      title: ''
      volume_number: 2
      total_pages: 1541
    bd7f252355c243649f0425592ef159af:
      image_group_id: I1PD95848
      title: ''
      volume_number: 3
      total_pages: 1687
    b6e00f1f084f4c039945ae6339a49911:
      image_group_id: I1PD95849
      title: ''
      volume_number: 4
      total_pages: 1678
    fb651c99481a4fe6b2a2b86d4caa58ec:
      image_group_id: I1PD95850
      title: ''
      volume_number: 5
      total_pages: 2069
    ce8b15e70e86455a81f3a1bd79c30bce:
      image_group_id: I1PD95851
      title: ''
      volume_number: 6
      total_pages: 1490
    b977795c6a1946819c0b7b63dbbae926:
      image_group_id: I1PD95852
      title: ''
      volume_number: 7
      total_pages: 1741
    4a9b8154276245439167a70ef0dda11e:
      image_group_id: I1PD95853
      title: ''
      volume_number: 8
      total_pages: 1661
    0214cba62224480f98cbb7183dd07d4a:
      image_group_id: I1PD95854
      title: ''
      volume_number: 9
      total_pages: 1794
    150bdc9a23b24de2afe3e89a2eefdb99:
      image_group_id: I1PD95855
      title: ''
      volume_number: 10
      total_pages: 1525
    35e963fc71284205afb7df114207f757:
      image_group_id: I1PD95856
      title: ''
      volume_number: 11
      total_pages: 2107
    2cf7fc1c02ad4165b2392fdda144df13:
      image_group_id: I1PD95857
      title: ''
      volume_number: 12
      total_pages: 1544
    d0e8664b544e47dea2eb667b293e46d9:
      image_group_id: I1PD95858
      title: ''
      volume_number: 13
      total_pages: 2043
    a7b449ae9b5e42dda45ee08c23e4619b:
      image_group_id: I1PD95859
      title: ''
      volume_number: 14
      total_pages: 1856
    203e62637cf84fb3a315c0b4aa17812b:
      image_group_id: I1PD95860
      title: ''
      volume_number: 15
      total_pages: 1453
    f7486bb808c14e28813b8b90105713e9:
      image_group_id: I1PD95861
      title: ''
      volume_number: 16
      total_pages: 1354
    10b1f9a3a6ac45f4ad37825cbc272422:
      image_group_id: I1PD95862
      title: ''
      volume_number: 17
      total_pages: 1158
    ea453d86cd3244f29c7dbdd4bd7e15df:
      image_group_id: I1PD95863
      title: ''
      volume_number: 18
      total_pages: 1634
    ddcfbe8ddff44c42864625addd319605:
      image_group_id: I1PD95864
      title: ''
      volume_number: 19
      total_pages: 1418
    c9e62feb5f1f46c68b1399f3f1866307:
      image_group_id: I1PD95865
      title: ''
      volume_number: 20
      total_pages: 1686
    e24d804c95994a33a7300dba7935d88d:
      image_group_id: I1PD95866
      title: ''
      volume_number: 21
      total_pages: 1477
    3a5d49cfcbf84d9589eee2ead416103e:
      image_group_id: I1PD95867
      title: ''
      volume_number: 22
      total_pages: 1409
    50437a960a57441583fe426500e6c1a3:
      image_group_id: I1PD95868
      title: ''
      volume_number: 23
      total_pages: 1660
    eda55486cd2d4b4da0b34dd764e0b9c5:
      image_group_id: I1PD95869
      title: ''
      volume_number: 24
      total_pages: 1586
    45ee65b1ff3843a3aa5569f14fd3fa6d:
      image_group_id: I1PD95870
      title: ''
      volume_number: 25
      total_pages: 1853
    358a656065224b0699ba9c63e774cdb2:
      image_group_id: I1PD95871
      title: ''
      volume_number: 26
      total_pages: 1902
    efb28ea347df40d08044c2c4524dcd42:
      image_group_id: I1PD95872
      title: ''
      volume_number: 27
      total_pages: 1953
    c4fd34b17fd04003ac48e09d26579d7b:
      image_group_id: I1PD95873
      title: ''
      volume_number: 28
      total_pages: 1445
    1f14dd7a119b4907ad22c7522b772dd8:
      image_group_id: I1PD95874
      title: ''
      volume_number: 29
      total_pages: 1781
    c52c759fbed84060b097c9b0810e888a:
      image_group_id: I1PD95875
      title: ''
      volume_number: 30
      total_pages: 1581
    f0c36d6b8a4647dc95e559fd7a3292ea:
      image_group_id: I1PD95876
      title: ''
      volume_number: 31
      total_pages: 1962
    f225ebec74dc4efcbe6092cd421ed1c6:
      image_group_id: I1PD95877
      title: ''
      volume_number: 32
      total_pages: 1582
    55ccfa16dbba411c8b613363bf5a7c02:
      image_group_id: I1PD95878
      title: ''
      volume_number: 33
      total_pages: 1810
    12e892527d96431997c31b9cf04d3d44:
      image_group_id: I1PD95879
      title: ''
      volume_number: 34
      total_pages: 1734
    22c4b0f3ec1f4ed582cdd10cc64d7057:
      image_group_id: I1PD95880
      title: ''
      volume_number: 35
      total_pages: 1722
    ff93010f891341ff8b5956e9687293ee:
      image_group_id: I1PD95881
      title: ''
      volume_number: 36
      total_pages: 1869
    8435fd5da53f4dd4b2ad1d36197aee99:
      image_group_id: I1PD95882
      title: ''
      volume_number: 37
      total_pages: 1379
    bc63ac434ac141f191fbf1f3c3e8259f:
      image_group_id: I1PD95883
      title: ''
      volume_number: 38
      total_pages: 1044
    14293e64426843f1a81191cd6a8b6912:
      image_group_id: I1PD95884
      title: ''
      volume_number: 39
      total_pages: 1625
    8a22727629ee49b4932500c36f1b0042:
      image_group_id: I1PD95885
      title: ''
      volume_number: 40
      total_pages: 1648
    a3e95894906d45c693a4d642f7a4fdad:
      image_group_id: I1PD95886
      title: ''
      volume_number: 41
      total_pages: 1349
    4a53ccf486a34f54b85f49240cb640cc:
      image_group_id: I1PD95887
      title: ''
      volume_number: 42
      total_pages: 1712
    af18bad93498445d83212f6be55dbf17:
      image_group_id: I1PD95888
      title: ''
      volume_number: 43
      total_pages: 1379
    6cb01d2911914cfa89c4dd92ff166e4c:
      image_group_id: I1PD95889
      title: ''
      volume_number: 44
      total_pages: 1381
    f5a6d365177d4072a34efa0bf73abcac:
      image_group_id: I1PD95890
      title: ''
      volume_number: 45
      total_pages: 1585
    be0e49e3f08a46669fe35c028d284200:
      image_group_id: I1PD95891
      title: ''
      volume_number: 46
      total_pages: 1201
    23671eb7936b4b75b455154dd3771bdd:
      image_group_id: I1PD95892
      title: ''
      volume_number: 47
      total_pages: 1464
    cb454679f4684614a06a78507aafc0d5:
      image_group_id: I1PD95893
      title: ''
      volume_number: 48
      total_pages: 1114
    92c86db3f801425488907a2149caa1fa:
      image_group_id: I1PD95894
      title: ''
      volume_number: 49
      total_pages: 1182
    0d6151ee72814a47833fa994bb22b5b8:
      image_group_id: I1PD95895
      title: ''
      volume_number: 50
      total_pages: 1666
    5bb233ec935d4e09bb07d28cb576d160:
      image_group_id: I1PD95896
      title: ''
      volume_number: 51
      total_pages: 1818
    acabd760cdfd4b6db25b791e8e774298:
      image_group_id: I1PD95897
      title: ''
      volume_number: 52
      total_pages: 1426
    520cf80b0dfc4b9f8a66cc067285c8bd:
      image_group_id: I1PD95898
      title: ''
      volume_number: 53
      total_pages: 1381
    8beab0abd8944b9c8e5c7e7937c908f8:
      image_group_id: I1PD95899
      title: ''
      volume_number: 54
      total_pages: 1470
    c88a01361343429e86e901b6ccbf9b5b:
      image_group_id: I1PD95900
      title: ''
      volume_number: 55
      total_pages: 1470
    9e8965d0bb6d4e5699599712e5613343:
      image_group_id: I1PD95901
      title: ''
      volume_number: 56
      total_pages: 1682
    2e2869b3b8184dd9aef0f5c1e525f152:
      image_group_id: I1PD95902
      title: ''
      volume_number: 57
      total_pages: 1605
    3b41428b6a1a419199e49d906735ba70:
      image_group_id: I1PD95903
      title: ''
      volume_number: 58
      total_pages: 1649
    ceae85c265784cf6ba8c6666bba4215f:
      image_group_id: I1PD95904
      title: ''
      volume_number: 59
      total_pages: 1834
    7b1b328afc8b4f1c9e8d873af1ec8d69:
      image_group_id: I1PD95905
      title: ''
      volume_number: 60
      total_pages: 1913
    7056bc22ec1c4c6996fdd17cba551032:
      image_group_id: I1PD95906
      title: ''
      volume_number: 61
      total_pages: 1877
    716b66ed5e0043a8953608f15f2c4064:
      image_group_id: I1PD95907
      title: ''
      volume_number: 62
      total_pages: 1557
    0d057b97249c4c46bb2b624c2a301705:
      image_group_id: I1PD95908
      title: ''
      volume_number: 63
      total_pages: 1926
    d932f60fd36047f2938298a2a84d9a0e:
      image_group_id: I1PD95909
      title: ''
      volume_number: 64
      total_pages: 1902
    3a4736c21093468db0c4c397c578fbb8:
      image_group_id: I1PD95910
      title: ''
      volume_number: 65
      total_pages: 1498
    b159726b6b9d4c01bada2cdac3e49fde:
      image_group_id: I1PD95911
      title: ''
      volume_number: 66
      total_pages: 1470
    7c275f8810264a37834d692fa723fc0d:
      image_group_id: I1PD95912
      title: ''
      volume_number: 67
      total_pages: 1529
    001f819c35e2460889e5e1fa12660344:
      image_group_id: I1PD95913
      title: ''
      volume_number: 68
      total_pages: 1478
    85838be1f9fd41c09523fbf2041355e7:
      image_group_id: I1PD95914
      title: ''
      volume_number: 69
      total_pages: 1538
    9a82e16b44e4418b8c551fd38ac0568e:
      image_group_id: I1PD95915
      title: ''
      volume_number: 70
      total_pages: 1505
    3677ad9317a847e5b4d6da948936fa39:
      image_group_id: I1PD95916
      title: ''
      volume_number: 71
      total_pages: 1683
    4054fb59369e4d358955d409f93e0f78:
      image_group_id: I1PD95917
      title: ''
      volume_number: 72
      total_pages: 1406
    1096439a041d4c05976ac3a60ea81df5:
      image_group_id: I1PD95918
      title: ''
      volume_number: 73
      total_pages: 1125
    7309e33dec6a4c6a9cfe1c946cc8c62b:
      image_group_id: I1PD95919
      title: ''
      volume_number: 74
      total_pages: 1618
    b2eb25c60aae44b48457a428a374bcda:
      image_group_id: I1PD95920
      title: ''
      volume_number: 75
      total_pages: 1529
    62b75ebbe56b430a915576a7488c839d:
      image_group_id: I1PD95921
      title: ''
      volume_number: 76
      total_pages: 1774
    9167cfc8bd9c41de8da58397a8f63f77:
      image_group_id: I1PD95922
      title: ''
      volume_number: 77
      total_pages: 1517
    bc9c2e4b348a4b058d6924f2979672d9:
      image_group_id: I1PD95923
      title: ''
      volume_number: 78
      total_pages: 1254
    643e464923064c52b46ef88af5f6a696:
      image_group_id: I1PD95924
      title: ''
      volume_number: 79
      total_pages: 1433
    1fe52951f4204fdcb1fc64d060aa4149:
      image_group_id: I1PD95925
      title: ''
      volume_number: 80
      total_pages: 1737
    32cb5ae51cbe48efb087b1a71a1e79fc:
      image_group_id: I1PD95926
      title: ''
      volume_number: 81
      total_pages: 1817
    33e7cfc78df14dfb8e725d6c8b9a246a:
      image_group_id: I1PD95927
      title: ''
      volume_number: 82
      total_pages: 1630
    15e290b0ec454461bd5cf926da3a2e06:
      image_group_id: I1PD95928
      title: ''
      volume_number: 83
      total_pages: 1296
    3e702313077d43478fb791138e9bf002:
      image_group_id: I1PD95929
      title: ''
      volume_number: 84
      total_pages: 1413
    db426a64681344938a5cd42e2cffd00f:
      image_group_id: I1PD95930
      title: ''
      volume_number: 85
      total_pages: 1621
    ca14b0a98cc747e7b7c9c613f0b16e98:
      image_group_id: I1PD95931
      title: ''
      volume_number: 86
      total_pages: 1409
    df758d8d594d45a99e0650419509200d:
      image_group_id: I1PD95932
      title: ''
      volume_number: 87
      total_pages: 1496
    163c49c25c4548bf9980a05cda99f16f:
      image_group_id: I1PD95933
      title: ''
      volume_number: 88
      total_pages: 1560
    5493de3f2349468a9cccdaf832380213:
      image_group_id: I1PD95934
      title: ''
      volume_number: 89
      total_pages: 1540
    0e24b3c0767a4c648b1f8184c864d61f:
      image_group_id: I1PD95935
      title: ''
      volume_number: 90
      total_pages: 1083
    9b6eb0ff6a7d4801b46b427a5009f559:
      image_group_id: I1PD95936
      title: ''
      volume_number: 91
      total_pages: 1078
    de8a6832ccb44b04a4d5cb0de279e93a:
      image_group_id: I1PD95937
      title: ''
      volume_number: 92
      total_pages: 1728
    00a657fd7df748f38260fcd66f08510c:
      image_group_id: I1PD95938
      title: ''
      volume_number: 93
      total_pages: 1484
    c6e70303aac642c18a986f963a788123:
      image_group_id: I1PD95939
      title: ''
      volume_number: 94
      total_pages: 1645
    70d160620a2f4c7e8134cb95799933dd:
      image_group_id: I1PD95940
      title: ''
      volume_number: 95
      total_pages: 1212
    80d2110fd9604d5fb2283080e43283da:
      image_group_id: I1PD95941
      title: ''
      volume_number: 96
      total_pages: 1144
    2c8c783f73134b9cad5fe3bbdb88034e:
      image_group_id: I1PD95942
      title: ''
      volume_number: 97
      total_pages: 1198
    11e63a178d2646adbeb34e27557dca04:
      image_group_id: I1PD95943
      title: ''
      volume_number: 98
      total_pages: 1825
    432cb9a8a72c46f3b2cfcce8c49cb179:
      image_group_id: I1PD95944
      title: ''
      volume_number: 99
      total_pages: 1625
    f0ecc17165ba468cbbd7148ac5e18aab:
      image_group_id: I1PD95945
      title: ''
      volume_number: 100
      total_pages: 1744
    ce45d5e8ae7b4f839909125320c59399:
      image_group_id: I1PD95946
      title: ''
      volume_number: 101
      total_pages: 1893
    1bb9cdc81f004903b3f5d6e9577ab429:
      image_group_id: I1PD95947
      title: ''
      volume_number: 102
      total_pages: 1476
    184724b1c1b542a89b84b3deb85982df:
      image_group_id: I1PD95948
      title: ''
      volume_number: 103
      total_pages: 1648
    949b9e2b25124b41a1ba8316aa155060:
      image_group_id: I1PD95949
      title: ''
      volume_number: 104
      total_pages: 1509
    6f3dd04cec2f446ba994e5b811de39b6:
      image_group_id: I1PD95950
      title: ''
      volume_number: 105
      total_pages: 910
    3162851108674f98a560c146d86d0b96:
      image_group_id: I1PD95951
      title: ''
      volume_number: 106
      total_pages: 1054
    862859a3e4264984b5d8192516d6a056:
      image_group_id: I1PD95952
      title: ''
      volume_number: 107
      total_pages: 1891
    b3657f168d6645699e884f9c0453c0a3:
      image_group_id: I1PD95953
      title: ''
      volume_number: 108
      total_pages: 1801
    856bd2adc9a1447a950c11562212e691:
      image_group_id: I1PD95954
      title: ''
      volume_number: 109
      total_pages: 1979
    68b66ac19e0547a6876084056202fc60:
      image_group_id: I1PD95955
      title: ''
      volume_number: 110
      total_pages: 1303
    9c99b7bb2ad14f98802a5b4978065c72:
      image_group_id: I1PD95956
      title: ''
      volume_number: 111
      total_pages: 1182
    a1430a625bc648e6aa59de17e8d68b69:
      image_group_id: I1PD95957
      title: ''
      volume_number: 112
      total_pages: 1143
    87b3eabfadeb46fcb76c4dc8e606dc66:
      image_group_id: I1PD95958
      title: ''
      volume_number: 113
      total_pages: 1744
    1ecc302e78d2431aa51a7a9feb174ffc:
      image_group_id: I1PD95959
      title: ''
      volume_number: 114
      total_pages: 1872
    f0f9904c053542878b1dec7429748365:
      image_group_id: I1PD95960
      title: ''
      volume_number: 115
      total_pages: 1829
    5191088f3a7f46208555bfef196cbf7b:
      image_group_id: I1PD95961
      title: ''
      volume_number: 116
      total_pages: 1880
    71941b6ff1c94d8a9ddb1b4c6085cdd6:
      image_group_id: I1PD95962
      title: ''
      volume_number: 117
      total_pages: 1208
    9296dfb53a644f67a1aded9f8f428736:
      image_group_id: I1PD95963
      title: ''
      volume_number: 118
      total_pages: 1080
    71c0f03c07fd4cee8865e5fcf41cc71b:
      image_group_id: I1PD95964
      title: ''
      volume_number: 119
      total_pages: 960
    60285b900a32475ca722a6424bdcd131:
      image_group_id: I1PD95965
      title: ''
      volume_number: 120
      total_pages: 1865
